### ISSUE TITLE
I'm a bit unsure: Is this ready for use, and how would I go about installing it to my project?

### ISSUE THREAD

**Issue by marens101** [ahlec/Alexandria#36]
Ok @ahlec, I have 2 questions:
1. Is Alexandria functional yet? (Like is it ready to be used in a project)

   and

2. I've only ever imported libs from NuGet and MyGet before, how would I install this to my project?

Any help is much appreciated,
-Max

**Comment by ahlec** [comment]
Hey! I'm super excited that you have an interest in this!

I think the core of Alexandria is getting there, but I still have a decent amount of work still left to do before I'm ready. One of the steps, in fact, is submitting it to NuGET. I was hoping that I'd be finished with v1 by the end of 2017, but I've still got a lot of work (mainly in the way of writing documentation and writing unit tests) so it's going to bleed over into the new year.

In the meantime, if you'd like to use the library, you're always free to download and build locally! You can download the source code, open up the .sln file and build the solution. Then, you can go to References > Add Reference and select the .dll that you just built. You'd want to choose Alexandria.dll in that case.

Between now and the time that I release the project on NuGET for v1.0.0, I'm liable to change some things (I've especially been eyeing a better solution for languages than just a built-in enum). But I think we're more or less settled on the framework overall.

If you do try it out, please let me know thoughts and feedback, and definitely report any bugs that you find along the way!!
